using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LoLQueryGraphSave
{
    class NameIndex
    {
        public static int[] ChampionIndex = new int[] { 412, 266, 23, 79, 69, 78, 13, 14, 1, 43, 111, 99, 103, 2, 112, 34, 86, 27, 127, 57, 25, 28, 105, 238, 74, 68, 82, 37, 55, 96, 22, 117, 30, 12, 122, 67, 110, 77, 126, 89, 134, 80, 121, 92, 42, 268, 51, 76, 3, 85, 45, 432, 150, 104, 90, 254, 10, 39, 64, 60, 420, 106, 20, 4, 24, 102, 429, 36, 223, 63, 131, 113, 8, 154, 421, 133, 84, 18, 120, 15, 236, 107, 19, 72, 54, 157, 101, 17, 75, 58, 119, 35, 50, 115, 91, 40, 245, 61, 9, 114, 31, 33, 7, 26, 16, 56, 222, 83, 6, 203, 21, 62, 53, 98, 201, 5, 29, 11, 44, 32, 41, 48, 38, 161, 143, 267, 59, 81 };
        public static string IndexParse(int index)
        {
            switch(index)
            {
                default:
                    return "Error";
                case 412:
                    return "Thresh";
                case 266:
                    return "Aatrox";
                case 23:
                    return "Tryndamere";
                case 79:
                    return "Gragas";
                case 69:
                    return "Cassiopeia";
                case 78:
                    return "Poppy";
                case 13:
                    return "Ryze";
                case 14:
                    return "Sion";
                case 1:
                    return "Annie";
                case 43:
                    return "Karma";
                case 111:
                    return "Nautilus";
                case 99:
                    return "Lux";
                case 103:
                    return "Ahri";
                case 2:
                    return "Olaf";
                case 112:
                    return "Viktor";
                case 34:
                    return "Anivia";
                case 86:
                    return "Garen";
                case 27:
                    return "Singed";
                case 127:
                    return "Lissandra";
                case 57:
                    return "Maokai";
                case 25:
                    return "Morgana";
                case 28:
                    return "Evelynn";
                case 105:
                    return "Fizz";
                case 238:
                    return "Zed";
                case 74:
                    return "Heimerdinger";
                case 68:
                    return "Rumble";
                case 82:
                    return "Mordekaiser";
                case 37:
                    return "Sona";
                case 55:
                    return "Katarina";
                case 96:
                    return "Kog'Maw";
                case 22:
                    return "Ashe";
                case 117:
                    return "Lulu";
                case 30:
                    return "Karthus";
                case 12:
                    return "Alistar";
                case 122:
                    return "Darius";
                case 67:
                    return "Vayne";
                case 110:
                    return "Varus";
                case 77:
                    return "Udyr";
                case 126:
                    return "Jayce";
                case 89:
                    return "Leona";
                case 134:
                    return "Syndra";
                case 80:
                    return "Pantheon";
                case 121:
                    return "Kha'Zix";
                case 92:
                    return "Riven";
                case 42:
                    return "Corki";
                case 268:
                    return "Azir";
                case 51:
                    return "Caitlyn";
                case 76:
                    return "Nidalee";
                case 3:
                    return "Galio";
                case 85:
                    return "Kennen";
                case 45:
                    return "Veigar";
                case 432:
                    return "Bard";
                case 150:
                    return "Gnar";
                case 104:
                    return "Graves";
                case 90:
                    return "Malzahar";
                case 254:
                    return "Vi";
                case 10:
                    return "Kayle";
                case 39:
                    return "Irelia";
                case 64:
                    return "Lee Sin";
                case 60:
                    return "Elise";
                case 420:
                    return "Illaoi";
                case 106:
                    return "Volibear";
                case 20:
                    return "Nunu";
                case 4:
                    return "Twisted Fate";
                case 24:
                    return "Jax";
                case 102:
                    return "Shyvana";
                case 429:
                    return "Kalista";
                case 36:
                    return "Dr. Mundo";
                case 223:
                    return "Tahm Kench";
                case 63:
                    return "Brand";
                case 131:
                    return "Diana";
                case 113:
                    return "Sejuani";
                case 8:
                    return "Vladimir";
                case 154:
                    return "Zac";
                case 421:
                    return "Rek'Sai";
                case 133:
                    return "Quinn";
                case 84:
                    return "Akali";
                case 18:
                    return "Tristana";
                case 120:
                    return "Hecarim";
                case 15:
                    return "Sivir";
                case 236:
                    return "Lucian";
                case 107:
                    return "Rengar";
                case 19:
                    return "Warwick";
                case 72:
                    return "Skarner";
                case 54:
                    return "Malphite";
                case 157:
                    return "Yasuo";
                case 101:
                    return "Xerath";
                case 17:
                    return "Teemo";
                case 75:
                    return "Nasus";
                case 58:
                    return "Renekton";
                case 119:
                    return "Draven";
                case 35:
                    return "Shaco";
                case 50:
                    return "Swain";
                case 115:
                    return "Ziggs";
                case 91:
                    return "Talon";
                case 40:
                    return "Janna";
                case 245:
                    return "Ekko";
                case 61:
                    return "Orianna";
                case 9:
                    return "Fiddlesticks";
                case 114:
                    return "Fiora";
                case 31:
                    return "Cho'Gath";
                case 33:
                    return "Rammus";
                case 7:
                    return "LeBlanc";
                case 26:
                    return "Zilean";
                case 16:
                    return "Soraka";
                case 56:
                    return "Nocturne";
                case 222:
                    return "Jinx";
                case 83:
                    return "Yorick";
                case 6:
                    return "Urgot";
                case 203:
                    return "Kindred";
                case 21:
                    return "Miss Fortune";
                case 62:
                    return "Wukong";
                case 53:
                    return "Blitzcrank";
                case 98:
                    return "Shen";
                case 201:
                    return "Braum";
                case 5:
                    return "Xin Zhao";
                case 29:
                    return "Twitch";
                case 11:
                    return "Master Yi";
                case 44:
                    return "Taric";
                case 32:
                    return "Amumu";
                case 41:
                    return "Gangplank";
                case 48:
                    return "Trundle";
                case 38:
                    return "Kassadin";
                case 161:
                    return "Vel'Koz";
                case 143:
                    return "Zyra";
                case 267:
                    return "Nami";
                case 59:
                    return "Jarvan IV";
                case 81:
                    return "Ezreal";
                case 999:
                    return "ChampionsAVG";



            }

        }
    }
}
